version: "3.9"

services:
  postgresql:
    container_name: postgres
    image: postgres:14
    environment:
      - POSTGRES_USER=michaelbbb
      - POSTGRES_PASSWORD=test_root_password
      - POSTGRES_DB=scrapper
    volumes:
      - ./migrations/pg-scrapper-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - backend

  liquibase-migrations:
    container_name: liquibase
    image: liquibase/liquibase:4.18
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 15
    command:
      - --hub-mode=off
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgres:5432/scrapper
      - --username=michaelbbb
      - --password=test_root_password
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend

networks:
  backend:
    driver: bridge